# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myGui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1374, 1002)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_originalImage = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_originalImage.sizePolicy().hasHeightForWidth())
        self.lbl_originalImage.setSizePolicy(sizePolicy)
        self.lbl_originalImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_originalImage.setObjectName("lbl_originalImage")
        self.horizontalLayout_4.addWidget(self.lbl_originalImage)
        self.lbl_greyImage = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_greyImage.sizePolicy().hasHeightForWidth())
        self.lbl_greyImage.setSizePolicy(sizePolicy)
        self.lbl_greyImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_greyImage.setObjectName("lbl_greyImage")
        self.horizontalLayout_4.addWidget(self.lbl_greyImage)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_browse = QtWidgets.QPushButton(self.centralWidget)
        self.btn_browse.setObjectName("btn_browse")
        self.verticalLayout_5.addWidget(self.btn_browse)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.rdbtn_linearScaling = QtWidgets.QRadioButton(self.groupBox)
        self.rdbtn_linearScaling.setEnabled(False)
        self.rdbtn_linearScaling.setObjectName("rdbtn_linearScaling")
        self.gridLayout.addWidget(self.rdbtn_linearScaling, 1, 0, 1, 2)
        self.rdbtn_histogramEqualization = QtWidgets.QRadioButton(self.groupBox)
        self.rdbtn_histogramEqualization.setEnabled(False)
        self.rdbtn_histogramEqualization.setObjectName("rdbtn_histogramEqualization")
        self.gridLayout.addWidget(self.rdbtn_histogramEqualization, 2, 0, 1, 2)
        self.rdbtn_threshold = QtWidgets.QRadioButton(self.groupBox)
        self.rdbtn_threshold.setEnabled(False)
        self.rdbtn_threshold.setObjectName("rdbtn_threshold")
        self.gridLayout.addWidget(self.rdbtn_threshold, 4, 0, 1, 1)
        self.rdbtn_negative = QtWidgets.QRadioButton(self.groupBox)
        self.rdbtn_negative.setEnabled(False)
        self.rdbtn_negative.setObjectName("rdbtn_negative")
        self.gridLayout.addWidget(self.rdbtn_negative, 0, 0, 1, 1)
        self.spbox_threshold = QtWidgets.QSpinBox(self.groupBox)
        self.spbox_threshold.setEnabled(False)
        self.spbox_threshold.setMaximum(255)
        self.spbox_threshold.setObjectName("spbox_threshold")
        self.gridLayout.addWidget(self.spbox_threshold, 4, 1, 1, 1)
        self.rdbtn_gradient = QtWidgets.QRadioButton(self.groupBox)
        self.rdbtn_gradient.setEnabled(False)
        self.rdbtn_gradient.setObjectName("rdbtn_gradient")
        self.gridLayout.addWidget(self.rdbtn_gradient, 3, 0, 1, 1)
        self.spbox_gradient = QtWidgets.QSpinBox(self.groupBox)
        self.spbox_gradient.setEnabled(False)
        self.spbox_gradient.setMinimum(1)
        self.spbox_gradient.setMaximum(255)
        self.spbox_gradient.setObjectName("spbox_gradient")
        self.gridLayout.addWidget(self.spbox_gradient, 3, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.wdgt_histred = PlotWidget(self.centralWidget)
        self.wdgt_histred.setObjectName("wdgt_histred")
        self.horizontalLayout_5.addWidget(self.wdgt_histred)
        self.wdgt_histgreen = PlotWidget(self.centralWidget)
        self.wdgt_histgreen.setObjectName("wdgt_histgreen")
        self.horizontalLayout_5.addWidget(self.wdgt_histgreen)
        self.wdgt_histblue = PlotWidget(self.centralWidget)
        self.wdgt_histblue.setObjectName("wdgt_histblue")
        self.horizontalLayout_5.addWidget(self.wdgt_histblue)
        self.wdgt_histgrey = PlotWidget(self.centralWidget)
        self.wdgt_histgrey.setObjectName("wdgt_histgrey")
        self.horizontalLayout_5.addWidget(self.wdgt_histgrey)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_redhist = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_redhist.setFont(font)
        self.lbl_redhist.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_redhist.setObjectName("lbl_redhist")
        self.horizontalLayout.addWidget(self.lbl_redhist)
        self.lbl_greenhist = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_greenhist.setFont(font)
        self.lbl_greenhist.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_greenhist.setObjectName("lbl_greenhist")
        self.horizontalLayout.addWidget(self.lbl_greenhist)
        self.lbl_bluehist = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_bluehist.setFont(font)
        self.lbl_bluehist.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_bluehist.setObjectName("lbl_bluehist")
        self.horizontalLayout.addWidget(self.lbl_bluehist)
        self.lbl_grayhist = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_grayhist.setFont(font)
        self.lbl_grayhist.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_grayhist.setObjectName("lbl_grayhist")
        self.horizontalLayout.addWidget(self.lbl_grayhist)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_modifiedImage = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_modifiedImage.sizePolicy().hasHeightForWidth())
        self.lbl_modifiedImage.setSizePolicy(sizePolicy)
        self.lbl_modifiedImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_modifiedImage.setObjectName("lbl_modifiedImage")
        self.horizontalLayout_6.addWidget(self.lbl_modifiedImage)
        self.wdgt_histmodifiedImage = PlotWidget(self.centralWidget)
        self.wdgt_histmodifiedImage.setObjectName("wdgt_histmodifiedImage")
        self.horizontalLayout_6.addWidget(self.wdgt_histmodifiedImage)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1374, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_originalImage.setText(_translate("MainWindow", "Colored Image"))
        self.lbl_greyImage.setText(_translate("MainWindow", "Gray Image"))
        self.btn_browse.setText(_translate("MainWindow", "Browse"))
        self.groupBox.setTitle(_translate("MainWindow", "Options"))
        self.rdbtn_linearScaling.setText(_translate("MainWindow", "Linear Scaling"))
        self.rdbtn_histogramEqualization.setText(_translate("MainWindow", "Histogram Equalization"))
        self.rdbtn_threshold.setText(_translate("MainWindow", "Threshold"))
        self.rdbtn_negative.setText(_translate("MainWindow", "Negative"))
        self.rdbtn_gradient.setText(_translate("MainWindow", "Gradient"))
        self.lbl_redhist.setText(_translate("MainWindow", "Red Channel Histogram"))
        self.lbl_greenhist.setText(_translate("MainWindow", "Green Channel Histogram"))
        self.lbl_bluehist.setText(_translate("MainWindow", "Blue Channel Histogram"))
        self.lbl_grayhist.setText(_translate("MainWindow", "Gray Histogram"))
        self.lbl_modifiedImage.setText(_translate("MainWindow", "Modified Image"))

from pyqtgraph import PlotWidget
