# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 997)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1220, 997))
        MainWindow.setMaximumSize(QtCore.QSize(1220, 997))
        MainWindow.setSizeIncrement(QtCore.QSize(1220, 997))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1220, 997))
        self.centralwidget.setMaximumSize(QtCore.QSize(1220, 997))
        self.centralwidget.setSizeIncrement(QtCore.QSize(1220, 997))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 561, 891))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblImage = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblImage.setFont(font)
        self.lblImage.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblImage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblImage.setTextFormat(QtCore.Qt.AutoText)
        self.lblImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblImage.setObjectName("lblImage")
        self.verticalLayout.addWidget(self.lblImage)
        self.lblLowPass = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblLowPass.setFont(font)
        self.lblLowPass.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblLowPass.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLowPass.setObjectName("lblLowPass")
        self.verticalLayout.addWidget(self.lblLowPass)
        self.lblHighPass = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblHighPass.setFont(font)
        self.lblHighPass.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblHighPass.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHighPass.setObjectName("lblHighPass")
        self.verticalLayout.addWidget(self.lblHighPass)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(590, 610, 581, 291))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnBrowse = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnBrowse.setObjectName("btnBrowse")
        self.verticalLayout_2.addWidget(self.btnBrowse)
        self.btnCameraOpen = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnCameraOpen.setObjectName("btnCameraOpen")
        self.verticalLayout_2.addWidget(self.btnCameraOpen)
        self.btnCameraClose = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnCameraClose.setObjectName("btnCameraClose")
        self.verticalLayout_2.addWidget(self.btnCameraClose)
        self.btnCapture = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnCapture.setObjectName("btnCapture")
        self.verticalLayout_2.addWidget(self.btnCapture)
        self.btnToggle = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnToggle.setObjectName("btnToggle")
        self.verticalLayout_2.addWidget(self.btnToggle)
        self.btnReset = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnReset.setObjectName("btnReset")
        self.verticalLayout_2.addWidget(self.btnReset)
        self.lblVideo = QtWidgets.QLabel(self.centralwidget)
        self.lblVideo.setGeometry(QtCore.QRect(600, 10, 601, 501))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lblVideo.setFont(font)
        self.lblVideo.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblVideo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblVideo.setObjectName("lblVideo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1220, 25))
        self.menubar.setObjectName("menubar")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Image = QtWidgets.QAction(MainWindow)
        self.actionSave_Image.setCheckable(False)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionSave_Low_Pass_Image = QtWidgets.QAction(MainWindow)
        self.actionSave_Low_Pass_Image.setObjectName("actionSave_Low_Pass_Image")
        self.actionSave_High_Pass_Image = QtWidgets.QAction(MainWindow)
        self.actionSave_High_Pass_Image.setObjectName("actionSave_High_Pass_Image")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuSave.addAction(self.actionSave_Image)
        self.menuSave.addAction(self.actionSave_Low_Pass_Image)
        self.menuSave.addAction(self.actionSave_High_Pass_Image)
        self.menuExit.addAction(self.actionExit)
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblImage.setText(_translate("MainWindow", "Original Image"))
        self.lblLowPass.setText(_translate("MainWindow", "Low Pass Filtered Image"))
        self.lblHighPass.setText(_translate("MainWindow", "High Pass Filtere Image"))
        self.btnBrowse.setText(_translate("MainWindow", "Browse"))
        self.btnCameraOpen.setText(_translate("MainWindow", "Open Camera"))
        self.btnCameraClose.setText(_translate("MainWindow", "Close Camera"))
        self.btnCapture.setText(_translate("MainWindow", "Capture"))
        self.btnToggle.setText(_translate("MainWindow", "Camera out of window"))
        self.btnReset.setText(_translate("MainWindow", "Reset"))
        self.lblVideo.setText(_translate("MainWindow", "Video Panel"))
        self.menuSave.setTitle(_translate("MainWindow", "Sa&ve"))
        self.menuExit.setTitle(_translate("MainWindow", "&Exit"))
        self.actionSave_Image.setText(_translate("MainWindow", "&Save Image"))
        self.actionSave_Image.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSave_Low_Pass_Image.setText(_translate("MainWindow", "Save &Low Pass Image"))
        self.actionSave_Low_Pass_Image.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionSave_High_Pass_Image.setText(_translate("MainWindow", "Save &High Pass Image"))
        self.actionSave_High_Pass_Image.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Esc"))

